# LLD I could not find logs for, so Japanese players likely have no elo ratings.
log_urls = [
    "http://crawl.akrasiac.org/logfile20",
    "http://crawl.akrasiac.org/logfile21",
    "http://crawl.akrasiac.org/logfile22",
    "http://crawl.akrasiac.org/logfile23",
    "http://crawl.akrasiac.org/logfile24",
    "http://crawl.akrasiac.org/logfile-git",
    "http://underhound.eu/crawl/meta/0.20/logfile",
    "http://underhound.eu/crawl/meta/0.21/logfile",
    "http://underhound.eu/crawl/meta/0.22/logfile",
    "http://underhound.eu/crawl/meta/0.23/logfile",
    "http://underhound.eu/crawl/meta/0.24/logfile",
    "http://underhound.eu/crawl/meta/git/logfile",
    "http://crawl.berotato.org/crawl/meta/0.20/logfile",
    "http://crawl.berotato.org/crawl/meta/0.21/logfile",
    "http://crawl.berotato.org/crawl/meta/0.22/logfile",
    "http://crawl.berotato.org/crawl/meta/0.23/logfile",
    "http://crawl.berotato.org/crawl/meta/0.24/logfile",
    "http://crawl.berotato.org/crawl/meta/git/logfile",
    "http://crawl.xtahua.com/crawl/meta/0.20/logfile",
    "http://crawl.xtahua.com/crawl/meta/0.21/logfile",
    "http://crawl.xtahua.com/crawl/meta/0.22/logfile",
    "http://crawl.xtahua.com/crawl/meta/0.23/logfile",
    "http://crawl.xtahua.com/crawl/meta/0.24/logfile",
    "http://crawl.xtahua.com/crawl/meta/git/logfile",
    "https://crawl.project357.org/dcss-logfile-0.20",
    "https://crawl.project357.org/dcss-logfiles-0.21",
    "https://crawl.project357.org/dcss-logfiles-0.22",
    "https://crawl.project357.org/dcss-logfiles-0.23",
    "https://crawl.project357.org/dcss-logfiles-0.24",
    "https://crawl.project357.org/dcss-logfiles-trunk",
    "https://crawl.kelbi.org/crawl/meta/0.21/logfile",
    "https://crawl.kelbi.org/crawl/meta/0.22/logfile",
    "https://crawl.kelbi.org/crawl/meta/0.23/logfile",
    "https://crawl.kelbi.org/crawl/meta/0.24/logfile",
    "https://crawl.kelbi.org/crawl/meta/git/logfile",
    "https://webzook.net/soup/0.20/logfile",
    "https://webzook.net/soup/0.21/logfile",
    "https://webzook.net/soup/0.22/logfile",
    "https://webzook.net/soup/0.23/logfile",
    "https://webzook.net/soup/0.24/logfile",
    "https://webzook.net/soup/trunk/logfile",
]

def filename_from_url(url):
    return url.replace("http://", "").replace("https://", "").replace("/", "-").replace(".", "-")